services:
  our-wedding:
    container_name: our-wedding
    build: .
    ports:
      - "3000:5173"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - our-wedding-network
    stdin_open: true
    tty: true

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: always
    networks:
      - our-wedding-network
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    environment:
      - MY_URL=${MY_URL:-}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile

networks:
  our-wedding-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: